# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

unbind C-b
set -g prefix C-j
bind C-j send-prefix

setw -g mode-keys vi
setw -g mouse on

bind-key L clear-history
bind-key r refresh-client
bind-key R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

bind-key \; copy-mode
bind-key a paste-buffer

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

setw -g monitor-activity on
set -g visual-activity on


# DESIGN TWEAKS
# --- Mocha Color Declaration ---
set -g @mocha_bg "#1e1e2e"
set -g @mocha_fg "#cdd6f4"
set -g @mocha_mauve "#cba6f7"
set -g @mocha_sapphire "#74c7ec"
set -g @mocha_peach "#fab387"
set -g @mocha_green "#a6e3a1"
set -g @mocha_surface "#313244"
set -g @mocha_sky "#89dceb"


# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# --- Status Bar General ---
set -g status-position top
set -g status-justify left
set -g status-interval 10
set -g status-style "bg=#{@thm_surface_0},fg=#{@thm_fg}"

# --- Right Side: Multi-Color Pills ---
set -g status-right-length 100
set -g status-right "" # Clear the default

# 1. Slurm Pill (Lavender)
set -ag status-right "#[fg=#{@mocha_fg},bg=#{@black}]#[fg=#{@mocha_fg},bg=#{@mocha_bg}]#[fg=#{@white}] SLURM#[fg=#{@white},bg=#{white},bold] #(~/.local/bin/tmux-slurm) #[fg=#{@mocha_fg},bg=#{@mocha_bg}]"

# Add a small transparent spacer between pills
#set -ag status-right " "

# 2. Time Pill (Sapphire)
set -ag status-right "#[fg=#{@thm_sapphire},bg=#{@thm_lavender}]#[fg=#{@thm_bg},bg=#{@thm_lavender}] %Y-%m-%d %H:%M %Z#[fg=#{@thm_sapphire},bg=#{@thm_lavender}]"

# Padding for the far right edge
set -ag status-right " "

set -g status-left ""
#set -g status-left-length 100
#set -g status-left "#[fg=#{@thm_green},bg=#{@thm_bg}]#[fg=#{@thm_bg},bg=#{@thm_green},bold]#S#[fg=#{@thm_green},bg=#{@thm_bg}]"

# 3. window status bar
set -g window-status-separator ""
setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #[bold]#I #[bold]#W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'


# messages
set -g message-style 'fg=yellow bg=red bold'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run 'bash ~/.tmux/plugins/tpm/tpm'

